<a href="https://colab.research.google.com/github/Aries2003/raiseLab/blob/main/RaiseLab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pyarrow

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyarrow in ./.local/lib/python3.12/site-packages (25.0.1)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd

# Read the English file line by line
with open(en_file_path, 'r', encoding='utf-8') as f:
    english_lines = f.readlines()

# Create a pandas DataFrame from the lines
en_df = pd.DataFrame({'english_text': [line.strip() for line in english_lines]})

print("\nEnglish DataFrame Head:")
display(en_df.head())

NameError: name 'en_file_path' is not defined

In [ ]:
# Read the Polish file line by line
with open(pl_file_path, 'r', encoding='utf-8') as f:
    polish_lines = f.readlines()

# Create a pandas DataFrame from the lines
pl_df = pd.DataFrame({'polish_text': [line.strip() for line in polish_lines]})

print("\nPolish DataFrame Head:")
display(pl_df.head())

Polish DataFrame Head:

                              polish_text
0             /W poprzednich odcinkach: /
1             - Chcesz zadzwonić do taty?
2  - Tak, powiem, że wszystko w porządku.
3                                 Dobrze.
4                  Lizzy, uważaj na męża.

QA

In [26]:
import pandas as pd

parquet_file_path = '/home/valmeid1/raiseLab/output/Translation/deepseek-r1.parquet'
df_parquet = pd.read_parquet(parquet_file_path, engine='pyarrow')

file_name = parquet_file_path.split('/')[-1]
print(f"File Name: {file_name}")

print("\nDataFrame Head:")
display(df_parquet.head())

File Name: deepseek-r1.parquet

DataFrame Head:

,source_text,reference_text,model_translation,model_name
0,/W poprzednich odcinkach: /,"Previously on ""The Blacklist""...",In previous episodes:,deepseek-r1
1,- Chcesz zadzwonić do taty?,- You want to call your daddy?,Do you want to call dad?,deepseek-r1
2,"- Tak, powiem, że wszystko w porządku.","- Yeah, I want to tell him I'm okay.","Yes, I will say everything is fine.",deepseek-r1
3,Dobrze.,Okay.,Good.,deepseek-r1
4,"Lizzy, uważaj na męża.",Lizzy... Be careful of your husband.,"Lizzy, be careful with your husband.",deepseek-r1

In [27]:
if 'id' in df_parquet.columns:
    df_parquet = df_parquet.drop(columns=['id'])

df_parquet['id'] = range(1, len(df_parquet) + 1)

print("\nDataFrame with new 'id' column:")
display(df_parquet.head())

DataFrame with new 'id' column:

,source_text,reference_text,model_translation,model_name,id
0,/W poprzednich odcinkach: /,"Previously on ""The Blacklist""...",In previous episodes:,deepseek-r1,1
1,- Chcesz zadzwonić do taty?,- You want to call your daddy?,Do you want to call dad?,deepseek-r1,2
2,"- Tak, powiem, że wszystko w porządku.","- Yeah, I want to tell him I'm okay.","Yes, I will say everything is fine.",deepseek-r1,3
3,Dobrze.,Okay.,Good.,deepseek-r1,4
4,"Lizzy, uważaj na męża.",Lizzy... Be careful of your husband.,"Lizzy, be careful with your husband.",deepseek-r1,5

In [28]:
output_parquet_file_path = '/home/valmeid1/raiseLab/output/Translation/deepseek-r1_processed.parquet'
df_parquet.to_parquet(output_parquet_file_path, index=False)

print(f"Processed DataFrame saved to: {output_parquet_file_path}")

Processed DataFrame saved to: /home/valmeid1/raiseLab/output/Translation/deepseek-r1_processed.parquet

In [29]:
import pandas as pd

parquet_file_path = '/home/valmeid1/raiseLab/output/Translation/gemma3-27b.parquet'
df_parquet = pd.read_parquet(parquet_file_path, engine='pyarrow')

file_name = parquet_file_path.split('/')[-1]
print(f"File Name: {file_name}")

print("\nDataFrame Head:")
display(df_parquet.head())

File Name: gemma3-27b.parquet

DataFrame Head:

,source_text,reference_text,model_translation,model_name
0,/W poprzednich odcinkach: /,"Previously on ""The Blacklist""...",Previously on…,gemma3:27b
1,- Chcesz zadzwonić do taty?,- You want to call your daddy?,Do you want to call Dad?,gemma3:27b
2,"- Tak, powiem, że wszystko w porządku.","- Yeah, I want to tell him I'm okay.","Yes, I will say that everything is fine.",gemma3:27b
3,Dobrze.,Okay.,Okay.,gemma3:27b
4,"Lizzy, uważaj na męża.",Lizzy... Be careful of your husband.,"Lizzy, beware of your husband.",gemma3:27b

In [30]:
if 'id' in df_parquet.columns:
    df_parquet = df_parquet.drop(columns=['id'])

df_parquet['id'] = range(1, len(df_parquet) + 1)

print("\nDataFrame with new 'id' column:")
display(df_parquet.head())

DataFrame with new 'id' column:

,source_text,reference_text,model_translation,model_name,id
0,/W poprzednich odcinkach: /,"Previously on ""The Blacklist""...",Previously on…,gemma3:27b,1
1,- Chcesz zadzwonić do taty?,- You want to call your daddy?,Do you want to call Dad?,gemma3:27b,2
2,"- Tak, powiem, że wszystko w porządku.","- Yeah, I want to tell him I'm okay.","Yes, I will say that everything is fine.",gemma3:27b,3
3,Dobrze.,Okay.,Okay.,gemma3:27b,4
4,"Lizzy, uważaj na męża.",Lizzy... Be careful of your husband.,"Lizzy, beware of your husband.",gemma3:27b,5

In [31]:
output_parquet_file_path = '/home/valmeid1/raiseLab/output/Translation/gemma3-27b_processed.parquet'
df_parquet.to_parquet(output_parquet_file_path, index=False)

print(f"Processed DataFrame saved to: {output_parquet_file_path}")

Processed DataFrame saved to: /home/valmeid1/raiseLab/output/Translation/gemma3-27b_processed.parquet

In [32]:
import pandas as pd

parquet_file_path = '/home/valmeid1/raiseLab/output/Translation/llama3.3-70b.parquet'
df_parquet = pd.read_parquet(parquet_file_path, engine='pyarrow')

file_name = parquet_file_path.split('/')[-1]
print(f"File Name: {file_name}")

print("\nDataFrame Head:")
display(df_parquet.head())

File Name: llama3.3-70b.parquet

DataFrame Head:

,source_text,reference_text,model_translation,model_name
0,/W poprzednich odcinkach: /,"Previously on ""The Blacklist""...",In previous episodes:,llama3.3:70b
1,- Chcesz zadzwonić do taty?,- You want to call your daddy?,Do you want to call daddy?,llama3.3:70b
2,"- Tak, powiem, że wszystko w porządku.","- Yeah, I want to tell him I'm okay.","Yes, I'll say that everything is fine.",llama3.3:70b
3,Dobrze.,Okay.,Good.,llama3.3:70b
4,"Lizzy, uważaj na męża.",Lizzy... Be careful of your husband.,"Lizzy, beware of your husband.",llama3.3:70b

In [33]:
if 'id' in df_parquet.columns:
    df_parquet = df_parquet.drop(columns=['id'])

df_parquet['id'] = range(1, len(df_parquet) + 1)

print("\nDataFrame with new 'id' column:")
display(df_parquet.head())

DataFrame with new 'id' column:

,source_text,reference_text,model_translation,model_name,id
0,/W poprzednich odcinkach: /,"Previously on ""The Blacklist""...",In previous episodes:,llama3.3:70b,1
1,- Chcesz zadzwonić do taty?,- You want to call your daddy?,Do you want to call daddy?,llama3.3:70b,2
2,"- Tak, powiem, że wszystko w porządku.","- Yeah, I want to tell him I'm okay.","Yes, I'll say that everything is fine.",llama3.3:70b,3
3,Dobrze.,Okay.,Good.,llama3.3:70b,4
4,"Lizzy, uważaj na męża.",Lizzy... Be careful of your husband.,"Lizzy, beware of your husband.",llama3.3:70b,5

In [34]:
output_parquet_file_path = '/home/valmeid1/raiseLab/output/Translation/llama3.3-70b_processed.parquet'
df_parquet.to_parquet(output_parquet_file_path, index=False)

print(f"Processed DataFrame saved to: {output_parquet_file_path}")

Processed DataFrame saved to: /home/valmeid1/raiseLab/output/Translation/llama3.3-70b_processed.parquet

In [35]:
import pandas as pd

parquet_file_path = '/home/valmeid1/raiseLab/output/Translation/mistral-small.parquet'
df_parquet = pd.read_parquet(parquet_file_path, engine='pyarrow')

file_name = parquet_file_path.split('/')[-1]
print(f"File Name: {file_name}")

print("\nDataFrame Head:")
display(df_parquet.head())

File Name: mistral-small.parquet

DataFrame Head:

,source_text,reference_text,model_translation,model_name
0,/W poprzednich odcinkach: /,"Previously on ""The Blacklist""...",In previous episodes:,mistral-small
1,- Chcesz zadzwonić do taty?,- You want to call your daddy?,- Do you want to call dad?,mistral-small
2,"- Tak, powiem, że wszystko w porządku.","- Yeah, I want to tell him I'm okay.","Yes, I'll say everything is fine.",mistral-small
3,Dobrze.,Okay.,Well,mistral-small
4,"Lizzy, uważaj na męża.",Lizzy... Be careful of your husband.,"Lizzy, beware of your husband",mistral-small

In [36]:
if 'id' in df_parquet.columns:
    df_parquet = df_parquet.drop(columns=['id'])

df_parquet['id'] = range(1, len(df_parquet) + 1)

print("\nDataFrame with new 'id' column:")
display(df_parquet.head())

DataFrame with new 'id' column:

,source_text,reference_text,model_translation,model_name,id
0,/W poprzednich odcinkach: /,"Previously on ""The Blacklist""...",In previous episodes:,mistral-small,1
1,- Chcesz zadzwonić do taty?,- You want to call your daddy?,- Do you want to call dad?,mistral-small,2
2,"- Tak, powiem, że wszystko w porządku.","- Yeah, I want to tell him I'm okay.","Yes, I'll say everything is fine.",mistral-small,3
3,Dobrze.,Okay.,Well,mistral-small,4
4,"Lizzy, uważaj na męża.",Lizzy... Be careful of your husband.,"Lizzy, beware of your husband",mistral-small,5

In [37]:
output_parquet_file_path = '/home/valmeid1/raiseLab/output/Translation/mistral-small_processed.parquet'
df_parquet.to_parquet(output_parquet_file_path, index=False)

print(f"Processed DataFrame saved to: {output_parquet_file_path}")

Processed DataFrame saved to: /home/valmeid1/raiseLab/output/Translation/mistral-small_processed.parquet

In [38]:
import pandas as pd

parquet_file_path = '/home/valmeid1/raiseLab/output/Translation/qwen3.6-27b.parquet'
df_parquet = pd.read_parquet(parquet_file_path, engine='pyarrow')

file_name = parquet_file_path.split('/')[-1]
print(f"File Name: {file_name}")

print("\nDataFrame Head:")
display(df_parquet.head())

File Name: qwen3.6-27b.parquet

DataFrame Head:

,source_text,reference_text,model_translation,model_name
0,/W poprzednich odcinkach: /,"Previously on ""The Blacklist""...",Previously on:,qwen3.6:27b
1,- Chcesz zadzwonić do taty?,- You want to call your daddy?,- Do you want to call Dad?,qwen3.6:27b
2,"- Tak, powiem, że wszystko w porządku.","- Yeah, I want to tell him I'm okay.","- Yes, I'll say everything is fine.",qwen3.6:27b
3,Dobrze.,Okay.,Okay.,qwen3.6:27b
4,"Lizzy, uważaj na męża.",Lizzy... Be careful of your husband.,"Lizzy, watch out for your husband.",qwen3.6:27b

In [39]:
if 'id' in df_parquet.columns:
    df_parquet = df_parquet.drop(columns=['id'])

df_parquet['id'] = range(1, len(df_parquet) + 1)

print("\nDataFrame with new 'id' column:")
display(df_parquet.head())

DataFrame with new 'id' column:

,source_text,reference_text,model_translation,model_name,id
0,/W poprzednich odcinkach: /,"Previously on ""The Blacklist""...",Previously on:,qwen3.6:27b,1
1,- Chcesz zadzwonić do taty?,- You want to call your daddy?,- Do you want to call Dad?,qwen3.6:27b,2
2,"- Tak, powiem, że wszystko w porządku.","- Yeah, I want to tell him I'm okay.","- Yes, I'll say everything is fine.",qwen3.6:27b,3
3,Dobrze.,Okay.,Okay.,qwen3.6:27b,4
4,"Lizzy, uważaj na męża.",Lizzy... Be careful of your husband.,"Lizzy, watch out for your husband.",qwen3.6:27b,5

In [40]:
output_parquet_file_path = '/home/valmeid1/raiseLab/output/Translation/qwen3.6-27b_processed.parquet'
df_parquet.to_parquet(output_parquet_file_path, index=False)

print(f"Processed DataFrame saved to: {output_parquet_file_path}")

Processed DataFrame saved to: /home/valmeid1/raiseLab/output/Translation/qwen3.6-27b_processed.parquet